[package]
name = "wipe-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "wipestation"
path = "src/main.rs"

[dependencies]
wipe-common = { path = "../wipe-common" }
wipe-engine = { path = "../wipe-engine" }
wipe-engine-mock = { path = "../wipe-engine-mock" }
wipe-cert = { path = "../wipe-cert" }
wipe-fleet = { path = "../wipe-fleet" }
wipe-server = { path = "../wipe-server" }
tokio = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }
time = { workspace = true }
